name: bottom
adopt-info: bottom
summary: A graphical process/system monitor with a customizable interface
description: |
  A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. 
  Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
  
  After installation, run the following commands so the program will run as intended:

    - sudo snap connect bottom:mount-observe

    - sudo snap connect bottom:network-control

    - sudo snap connect bottom:hardware-observe

    - sudo snap connect bottom:system-observe

    - sudo snap connect bottom:process-control

    - sudo snap connect bottom:physical-memory-observe
    
  Check out the developer's site for more usage hints: https://github.com/ClementTsang/bottom#usage
  
license: MIT

base: core18
grade: stable
confinement: strict

apps: 
  bottom:
    command: btm
    plugs:
      - mount-observe
      - network-control
      - process-control
      - system-observe
      - hardware-observe
      - network
      
parts:
  bottom:
    source: https://github.com/ClementTsang/bottom
    source-type: git
    plugin: rust
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
      
    build-packages:
      - rustc
      - cargo
      
