name: bottom
adopt-info: bottom
summary: A graphical process/system monitor with a customizable interface
description: |
  A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. 
  Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
  
  After installation, run the following commands so the program will run as intended:

    - sudo snap connect bottom:mount-observe

    - sudo snap connect bottom:hardware-observe

    - sudo snap connect bottom:system-observe

    - sudo snap connect bottom:process-control

  
  Check out the developer's site for more usage hints: https://github.com/ClementTsang/bottom#usage
  
license: MIT

base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  
apps: 
  bottom:
    command: bin/btm
    plugs:
      - mount-observe
      - network-control
      - process-control
      - system-observe
      - hardware-observe
      - network
      
parts:
  bottom:
    source: https://github.com/ClementTsang/bottom
    source-type: git
    plugin: rust
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - rustc
      - cargo
      - python3-toml
      - tzdata
