name: bottom
adopt-info: bottom
summary: A graphical process/system monitor with a customizable interface
description: |
  A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. 
  Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
  
  After installation, run the following commands so the program will run as intended:

    - sudo snap connect bottom:mount-observe

    - sudo snap connect bottom:hardware-observe

    - sudo snap connect bottom:system-observe

    - sudo snap connect bottom:process-control

  
  Check out the developer's site for more usage hints: https://github.com/ClementTsang/bottom#usage
  
license: MIT

base: core24
grade: stable
confinement: strict
compression: lzo
issues: https://github.com/kz6fittycent/bottom/issues
source-code: https://github.com/ClementTsang/bottom
contact: https://github.com/kz6fittycent/bottom

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]

apps: 
  bottom:
    command: bin/btm
    plugs:
      - mount-observe
      - network-control
      - process-control
      - system-observe
      - hardware-observe
      - network
      
parts:
  bottom:
    source: https://github.com/ClementTsang/bottom
    source-type: git
    source-branch: release
    plugin: rust
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
      
    build-packages:
      - rustc
      - cargo
      - python3-toml
      - tzdata
